sudo: false
language: scala
dist: trusty
scala:
  - "2.12.1"
script:
  - sbt clean coverage coreJVM/test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sbt coveralls
branches:
  only:
    - master
cache:
  directories:
    $HOME/.ivy2/cache
jdk:
  - openjdk8
